/* Generated by Yosys 0.60+78 (git sha1 156752695, clang++ 18.1.8 -fPIC -O3) */

(* hdlname = "csi_top" *)
(* top =  1  *)
(* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:3.1-45.10" *)
module csi_top(clk_ext, LED);
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:7.12-7.19" *)
  input clk_ext;
  wire clk_ext;
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:9.15-9.18" *)
  output [7:0] LED;
  wire [7:0] LED;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  (* force_downto = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:34.17-34.30|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:51.21-51.22" *)
  wire [7:0] _075_;
  (* force_downto = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:34.17-34.30|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:37.23-37.25" *)
  (* unused_bits = "7" *)
  wire [7:0] _076_;
  (* force_downto = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:34.17-34.30|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:33.26-33.27" *)
  wire [7:0] _077_;
  (* force_downto = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:51.21-51.22" *)
  wire [21:0] _078_;
  (* force_downto = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:37.23-37.25" *)
  (* unused_bits = "21" *)
  wire [21:0] _079_;
  (* force_downto = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:33.26-33.27" *)
  wire [21:0] _080_;
  (* force_downto = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:12.24-12.48|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:29.22-29.23" *)
  wire [0:0] _081_;
  (* force_downto = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:12.24-12.48|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:51.21-51.22" *)
  wire [5:0] _082_;
  (* force_downto = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:12.24-12.48|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:37.23-37.25" *)
  (* unused_bits = "5" *)
  wire [5:0] _083_;
  (* force_downto = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:12.24-12.48|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:33.26-33.27" *)
  wire [5:0] _084_;
  wire _085_;
  (* hdlname = "clkrst_gen_inst clk_ref" *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:4.11-4.18" *)
  wire \clkrst_gen_inst.clk_ref ;
  (* hdlname = "clkrst_gen_inst rst_ref_cnt" *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:8.15-8.26" *)
  wire [5:0] \clkrst_gen_inst.rst_ref_cnt ;
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:22.13-22.20" *)
  wire [21:0] counter;
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:23.12-23.21" *)
  wire [7:0] led_count;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:406.7-409.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'h8),
    .INIT_L10(4'h8)
  ) _086_ (
    .I0(\clkrst_gen_inst.rst_ref_cnt [0]),
    .I1(\clkrst_gen_inst.rst_ref_cnt [1]),
    .I2(\clkrst_gen_inst.rst_ref_cnt [2]),
    .I3(\clkrst_gen_inst.rst_ref_cnt [5]),
    .O(_046_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _087_ (
    .I0(\clkrst_gen_inst.rst_ref_cnt [3]),
    .I1(\clkrst_gen_inst.rst_ref_cnt [4]),
    .I2(_046_),
    .O(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:18.7-21.6" *)
  CC_LUT2 #(
    .INIT(4'h8)
  ) _088_ (
    .I0(counter[0]),
    .I1(counter[1]),
    .O(_048_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:418.7-421.6" *)
  CC_L2T5 #(
    .INIT_L02(4'h1),
    .INIT_L03(4'h4),
    .INIT_L11(4'h8),
    .INIT_L20(4'h4)
  ) _089_ (
    .I0(counter[4]),
    .I1(counter[5]),
    .I2(counter[8]),
    .I3(_048_),
    .I4(counter[3]),
    .O(_049_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:49.7-52.6" *)
  CC_LUT2 #(
    .INIT(4'he)
  ) _090_ (
    .I0(counter[13]),
    .I1(counter[14]),
    .O(_050_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:406.7-409.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h1),
    .INIT_L01(4'h1),
    .INIT_L10(4'h8)
  ) _091_ (
    .I0(counter[13]),
    .I1(counter[14]),
    .I2(counter[15]),
    .I3(counter[16]),
    .O(_051_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:148.7-151.6" *)
  CC_L2T4 #(
    .INIT_L00(4'he),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _092_ (
    .I0(counter[15]),
    .I1(counter[16]),
    .I2(_050_),
    .O(_052_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:49.7-52.6" *)
  CC_LUT2 #(
    .INIT(4'he)
  ) _093_ (
    .I0(counter[9]),
    .I1(counter[10]),
    .O(_053_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:49.7-52.6" *)
  CC_LUT2 #(
    .INIT(4'he)
  ) _094_ (
    .I0(counter[11]),
    .I1(counter[12]),
    .O(_054_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:406.7-409.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h1),
    .INIT_L01(4'h1),
    .INIT_L10(4'h8)
  ) _095_ (
    .I0(counter[9]),
    .I1(counter[10]),
    .I2(counter[11]),
    .I3(counter[12]),
    .O(_055_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:148.7-151.6" *)
  CC_L2T4 #(
    .INIT_L00(4'he),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _096_ (
    .I0(_052_),
    .I1(_053_),
    .I2(_054_),
    .O(_056_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:49.7-52.6" *)
  CC_LUT2 #(
    .INIT(4'hb)
  ) _097_ (
    .I0(counter[21]),
    .I1(counter[2]),
    .O(_057_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:49.7-52.6" *)
  CC_LUT2 #(
    .INIT(4'h7)
  ) _098_ (
    .I0(counter[6]),
    .I1(counter[7]),
    .O(_058_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:406.7-409.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h4),
    .INIT_L01(4'h8),
    .INIT_L10(4'h8)
  ) _099_ (
    .I0(counter[21]),
    .I1(counter[2]),
    .I2(counter[6]),
    .I3(counter[7]),
    .O(_059_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:49.7-52.6" *)
  CC_LUT2 #(
    .INIT(4'he)
  ) _100_ (
    .I0(counter[17]),
    .I1(counter[18]),
    .O(_060_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:148.7-151.6" *)
  CC_L2T4 #(
    .INIT_L00(4'he),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _101_ (
    .I0(counter[19]),
    .I1(counter[20]),
    .I2(_060_),
    .O(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:418.7-421.6" *)
  CC_L2T5 #(
    .INIT_L02(4'h1),
    .INIT_L03(4'h4),
    .INIT_L11(4'h8),
    .INIT_L20(4'h4)
  ) _102_ (
    .I0(counter[18]),
    .I1(counter[19]),
    .I2(counter[20]),
    .I3(_059_),
    .I4(counter[17]),
    .O(_062_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:148.7-151.6" *)
  CC_L2T4 #(
    .INIT_L00(4'he),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _103_ (
    .I0(_057_),
    .I1(_058_),
    .I2(_061_),
    .O(_063_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:406.7-409.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'h8),
    .INIT_L10(4'h8)
  ) _104_ (
    .I0(_049_),
    .I1(_051_),
    .I2(_055_),
    .I3(_062_),
    .O(_064_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:148.7-151.6" *)
  CC_L2T4 #(
    .INIT_L00(4'hd),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _105_ (
    .I0(_049_),
    .I1(_056_),
    .I2(_063_),
    .O(_065_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:18.7-21.6" *)
  CC_LUT2 #(
    .INIT(4'h8)
  ) _106_ (
    .I0(_047_),
    .I1(_065_),
    .O(_066_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _107_ (
    .I0(_077_[7]),
    .I1(_047_),
    .I2(_064_),
    .O(_067_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _108_ (
    .I0(led_count[7]),
    .I1(_066_),
    .I2(_067_),
    .O(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _109_ (
    .I0(_077_[6]),
    .I1(_047_),
    .I2(_064_),
    .O(_068_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _110_ (
    .I0(led_count[6]),
    .I1(_066_),
    .I2(_068_),
    .O(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _111_ (
    .I0(_077_[5]),
    .I1(_047_),
    .I2(_064_),
    .O(_069_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _112_ (
    .I0(led_count[5]),
    .I1(_066_),
    .I2(_069_),
    .O(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _113_ (
    .I0(_077_[4]),
    .I1(_047_),
    .I2(_064_),
    .O(_070_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _114_ (
    .I0(led_count[4]),
    .I1(_066_),
    .I2(_070_),
    .O(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _115_ (
    .I0(_077_[3]),
    .I1(_047_),
    .I2(_064_),
    .O(_071_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _116_ (
    .I0(led_count[3]),
    .I1(_066_),
    .I2(_071_),
    .O(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _117_ (
    .I0(_077_[2]),
    .I1(_047_),
    .I2(_064_),
    .O(_072_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _118_ (
    .I0(led_count[2]),
    .I1(_066_),
    .I2(_072_),
    .O(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _119_ (
    .I0(_077_[1]),
    .I1(_047_),
    .I2(_064_),
    .O(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _120_ (
    .I0(led_count[1]),
    .I1(_066_),
    .I2(_073_),
    .O(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _121_ (
    .I0(_077_[0]),
    .I1(_047_),
    .I2(_064_),
    .O(_074_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _122_ (
    .I0(led_count[0]),
    .I1(_066_),
    .I2(_074_),
    .O(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _123_ (
    .I0(_080_[21]),
    .I1(_047_),
    .I2(_065_),
    .O(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _124_ (
    .I0(_080_[20]),
    .I1(_047_),
    .I2(_065_),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _125_ (
    .I0(_080_[19]),
    .I1(_047_),
    .I2(_065_),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _126_ (
    .I0(_080_[18]),
    .I1(_047_),
    .I2(_065_),
    .O(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _127_ (
    .I0(_080_[17]),
    .I1(_047_),
    .I2(_065_),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _128_ (
    .I0(_080_[16]),
    .I1(_047_),
    .I2(_065_),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _129_ (
    .I0(_080_[15]),
    .I1(_047_),
    .I2(_065_),
    .O(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _130_ (
    .I0(_080_[14]),
    .I1(_047_),
    .I2(_065_),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _131_ (
    .I0(_080_[13]),
    .I1(_047_),
    .I2(_065_),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _132_ (
    .I0(_080_[12]),
    .I1(_047_),
    .I2(_065_),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _133_ (
    .I0(_080_[11]),
    .I1(_047_),
    .I2(_065_),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _134_ (
    .I0(_080_[10]),
    .I1(_047_),
    .I2(_065_),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _135_ (
    .I0(_080_[9]),
    .I1(_047_),
    .I2(_065_),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _136_ (
    .I0(_080_[8]),
    .I1(_047_),
    .I2(_065_),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _137_ (
    .I0(_080_[7]),
    .I1(_047_),
    .I2(_065_),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _138_ (
    .I0(_080_[6]),
    .I1(_047_),
    .I2(_065_),
    .O(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _139_ (
    .I0(_080_[5]),
    .I1(_047_),
    .I2(_065_),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _140_ (
    .I0(_080_[4]),
    .I1(_047_),
    .I2(_065_),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _141_ (
    .I0(_080_[3]),
    .I1(_047_),
    .I2(_065_),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _142_ (
    .I0(_080_[2]),
    .I1(_047_),
    .I2(_065_),
    .O(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _143_ (
    .I0(_080_[1]),
    .I1(_047_),
    .I2(_065_),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:113.7-116.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h8)
  ) _144_ (
    .I0(_080_[0]),
    .I1(_047_),
    .I2(_065_),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _145_ (
    .I0(_045_),
    .I1(_066_),
    .I2(_067_),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _146_ (
    .I0(_044_),
    .I1(_066_),
    .I2(_068_),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _147_ (
    .I0(_043_),
    .I1(_066_),
    .I2(_069_),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _148_ (
    .I0(_042_),
    .I1(_066_),
    .I2(_070_),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _149_ (
    .I0(_041_),
    .I1(_066_),
    .I2(_071_),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _150_ (
    .I0(_040_),
    .I1(_066_),
    .I2(_072_),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _151_ (
    .I0(_039_),
    .I1(_066_),
    .I2(_073_),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/lut_tree_map.v:218.7-221.6" *)
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'he)
  ) _152_ (
    .I0(_038_),
    .I1(_066_),
    .I2(_074_),
    .O(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:34.17-34.30|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _153_ (
    .A(1'h1),
    .B(led_count[0]),
    .CI(1'h0),
    .CO(_075_[1]),
    .S(_077_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:34.17-34.30|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _154_ (
    .A(1'h0),
    .B(led_count[1]),
    .CI(_075_[1]),
    .CO(_075_[2]),
    .S(_077_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:34.17-34.30|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _155_ (
    .A(1'h0),
    .B(led_count[2]),
    .CI(_075_[2]),
    .CO(_075_[3]),
    .S(_077_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:34.17-34.30|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _156_ (
    .A(1'h0),
    .B(led_count[3]),
    .CI(_075_[3]),
    .CO(_075_[4]),
    .S(_077_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:34.17-34.30|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _157_ (
    .A(1'h0),
    .B(led_count[4]),
    .CI(_075_[4]),
    .CO(_075_[5]),
    .S(_077_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:34.17-34.30|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _158_ (
    .A(1'h0),
    .B(led_count[5]),
    .CI(_075_[5]),
    .CO(_075_[6]),
    .S(_077_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:34.17-34.30|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _159_ (
    .A(1'h0),
    .B(led_count[6]),
    .CI(_075_[6]),
    .CO(_075_[7]),
    .S(_077_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:34.17-34.30|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _160_ (
    .A(1'h0),
    .B(led_count[7]),
    .CI(_075_[7]),
    .CO(_076_[7]),
    .S(_077_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _161_ (
    .A(1'h1),
    .B(counter[0]),
    .CI(1'h0),
    .CO(_078_[1]),
    .S(_080_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _162_ (
    .A(1'h0),
    .B(counter[10]),
    .CI(_078_[10]),
    .CO(_078_[11]),
    .S(_080_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _163_ (
    .A(1'h0),
    .B(counter[11]),
    .CI(_078_[11]),
    .CO(_078_[12]),
    .S(_080_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _164_ (
    .A(1'h0),
    .B(counter[12]),
    .CI(_078_[12]),
    .CO(_078_[13]),
    .S(_080_[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _165_ (
    .A(1'h0),
    .B(counter[13]),
    .CI(_078_[13]),
    .CO(_078_[14]),
    .S(_080_[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _166_ (
    .A(1'h0),
    .B(counter[14]),
    .CI(_078_[14]),
    .CO(_078_[15]),
    .S(_080_[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _167_ (
    .A(1'h0),
    .B(counter[15]),
    .CI(_078_[15]),
    .CO(_078_[16]),
    .S(_080_[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _168_ (
    .A(1'h0),
    .B(counter[16]),
    .CI(_078_[16]),
    .CO(_078_[17]),
    .S(_080_[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _169_ (
    .A(1'h0),
    .B(counter[17]),
    .CI(_078_[17]),
    .CO(_078_[18]),
    .S(_080_[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _170_ (
    .A(1'h0),
    .B(counter[18]),
    .CI(_078_[18]),
    .CO(_078_[19]),
    .S(_080_[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _171_ (
    .A(1'h0),
    .B(counter[19]),
    .CI(_078_[19]),
    .CO(_078_[20]),
    .S(_080_[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _172_ (
    .A(1'h0),
    .B(counter[1]),
    .CI(_078_[1]),
    .CO(_078_[2]),
    .S(_080_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _173_ (
    .A(1'h0),
    .B(counter[20]),
    .CI(_078_[20]),
    .CO(_078_[21]),
    .S(_080_[20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _174_ (
    .A(1'h0),
    .B(counter[21]),
    .CI(_078_[21]),
    .CO(_079_[21]),
    .S(_080_[21])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _175_ (
    .A(1'h0),
    .B(counter[2]),
    .CI(_078_[2]),
    .CO(_078_[3]),
    .S(_080_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _176_ (
    .A(1'h0),
    .B(counter[3]),
    .CI(_078_[3]),
    .CO(_078_[4]),
    .S(_080_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _177_ (
    .A(1'h0),
    .B(counter[4]),
    .CI(_078_[4]),
    .CO(_078_[5]),
    .S(_080_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _178_ (
    .A(1'h0),
    .B(counter[5]),
    .CI(_078_[5]),
    .CO(_078_[6]),
    .S(_080_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _179_ (
    .A(1'h0),
    .B(counter[6]),
    .CI(_078_[6]),
    .CO(_078_[7]),
    .S(_080_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _180_ (
    .A(1'h0),
    .B(counter[7]),
    .CI(_078_[7]),
    .CO(_078_[8]),
    .S(_080_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _181_ (
    .A(1'h0),
    .B(counter[8]),
    .CI(_078_[8]),
    .CO(_078_[9]),
    .S(_080_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:37.15-37.26|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _182_ (
    .A(1'h0),
    .B(counter[9]),
    .CI(_078_[9]),
    .CO(_078_[10]),
    .S(_080_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:12.24-12.48|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _183_ (
    .A(_081_),
    .B(\clkrst_gen_inst.rst_ref_cnt [0]),
    .CI(1'h0),
    .CO(_082_[1]),
    .S(_084_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:12.24-12.48|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _184_ (
    .A(1'h0),
    .B(\clkrst_gen_inst.rst_ref_cnt [1]),
    .CI(_082_[1]),
    .CO(_082_[2]),
    .S(_084_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:12.24-12.48|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _185_ (
    .A(1'h0),
    .B(\clkrst_gen_inst.rst_ref_cnt [2]),
    .CI(_082_[2]),
    .CO(_082_[3]),
    .S(_084_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:12.24-12.48|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _186_ (
    .A(1'h0),
    .B(\clkrst_gen_inst.rst_ref_cnt [3]),
    .CI(_082_[3]),
    .CO(_082_[4]),
    .S(_084_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:12.24-12.48|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _187_ (
    .A(1'h0),
    .B(\clkrst_gen_inst.rst_ref_cnt [4]),
    .CI(_082_[4]),
    .CO(_082_[5]),
    .S(_084_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:12.24-12.48|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/arith_map.v:57.12-63.5" *)
  CC_ADDF _188_ (
    .A(1'h0),
    .B(\clkrst_gen_inst.rst_ref_cnt [5]),
    .CI(_082_[5]),
    .CO(_083_[5]),
    .S(_084_[5])
  );
  CC_BUFG _189_ (
    .I(_085_),
    .O(\clkrst_gen_inst.clk_ref )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _190_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_000_),
    .EN(1'h1),
    .Q(_038_),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _191_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_001_),
    .EN(1'h1),
    .Q(_039_),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _192_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_002_),
    .EN(1'h1),
    .Q(_040_),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _193_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_003_),
    .EN(1'h1),
    .Q(_041_),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _194_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_004_),
    .EN(1'h1),
    .Q(_042_),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _195_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_005_),
    .EN(1'h1),
    .Q(_043_),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _196_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_006_),
    .EN(1'h1),
    .Q(_044_),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _197_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_007_),
    .EN(1'h1),
    .Q(_045_),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _198_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_008_),
    .EN(1'h1),
    .Q(counter[0]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _199_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_009_),
    .EN(1'h1),
    .Q(counter[1]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _200_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_010_),
    .EN(1'h1),
    .Q(counter[2]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _201_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_011_),
    .EN(1'h1),
    .Q(counter[3]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _202_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_012_),
    .EN(1'h1),
    .Q(counter[4]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _203_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_013_),
    .EN(1'h1),
    .Q(counter[5]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _204_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_014_),
    .EN(1'h1),
    .Q(counter[6]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _205_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_015_),
    .EN(1'h1),
    .Q(counter[7]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _206_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_016_),
    .EN(1'h1),
    .Q(counter[8]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _207_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_017_),
    .EN(1'h1),
    .Q(counter[9]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _208_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_018_),
    .EN(1'h1),
    .Q(counter[10]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _209_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_019_),
    .EN(1'h1),
    .Q(counter[11]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _210_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_020_),
    .EN(1'h1),
    .Q(counter[12]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _211_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_021_),
    .EN(1'h1),
    .Q(counter[13]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _212_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_022_),
    .EN(1'h1),
    .Q(counter[14]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _213_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_023_),
    .EN(1'h1),
    .Q(counter[15]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _214_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_024_),
    .EN(1'h1),
    .Q(counter[16]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _215_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_025_),
    .EN(1'h1),
    .Q(counter[17]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _216_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_026_),
    .EN(1'h1),
    .Q(counter[18]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _217_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_027_),
    .EN(1'h1),
    .Q(counter[19]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _218_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_028_),
    .EN(1'h1),
    .Q(counter[20]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _219_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_029_),
    .EN(1'h1),
    .Q(counter[21]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _220_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_030_),
    .EN(1'h1),
    .Q(led_count[0]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _221_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_031_),
    .EN(1'h1),
    .Q(led_count[1]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _222_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_032_),
    .EN(1'h1),
    .Q(led_count[2]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _223_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_033_),
    .EN(1'h1),
    .Q(led_count[3]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _224_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_034_),
    .EN(1'h1),
    .Q(led_count[4]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _225_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_035_),
    .EN(1'h1),
    .Q(led_count[5]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _226_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_036_),
    .EN(1'h1),
    .Q(led_count[6]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/csi_top.v:25.1-40.4|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _227_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_037_),
    .EN(1'h1),
    .Q(led_count[7]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:11.5-13.8|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _228_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_084_[0]),
    .EN(1'h1),
    .Q(\clkrst_gen_inst.rst_ref_cnt [0]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:11.5-13.8|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _229_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_084_[1]),
    .EN(1'h1),
    .Q(\clkrst_gen_inst.rst_ref_cnt [1]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:11.5-13.8|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _230_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_084_[2]),
    .EN(1'h1),
    .Q(\clkrst_gen_inst.rst_ref_cnt [2]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:11.5-13.8|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _231_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_084_[3]),
    .EN(1'h1),
    .Q(\clkrst_gen_inst.rst_ref_cnt [3]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:11.5-13.8|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _232_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_084_[4]),
    .EN(1'h1),
    .Q(\clkrst_gen_inst.rst_ref_cnt [4]),
    .SR(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/mark/oss-cad-suite/hw_simple/RTL/clkrst_gen.v:11.5-13.8|/home/mark/oss-cad-suite/lib/../share/yosys/gatemate/reg_map.v:32.4-32.61" *)
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _233_ (
    .CLK(\clkrst_gen_inst.clk_ref ),
    .D(_084_[5]),
    .EN(1'h1),
    .Q(\clkrst_gen_inst.rst_ref_cnt [5]),
    .SR(1'h0)
  );
  CC_L2T4 #(
    .INIT_L00(4'h8),
    .INIT_L01(4'ha),
    .INIT_L10(4'h7)
  ) _234_ (
    .I0(\clkrst_gen_inst.rst_ref_cnt [3]),
    .I1(\clkrst_gen_inst.rst_ref_cnt [4]),
    .I2(_046_),
    .O(_081_)
  );
  (* keep = 32'd1 *)
  CC_OBUF _235_ (
    .A(_038_),
    .O(LED[0])
  );
  (* keep = 32'd1 *)
  CC_OBUF _236_ (
    .A(_039_),
    .O(LED[1])
  );
  (* keep = 32'd1 *)
  CC_OBUF _237_ (
    .A(_040_),
    .O(LED[2])
  );
  (* keep = 32'd1 *)
  CC_OBUF _238_ (
    .A(_041_),
    .O(LED[3])
  );
  (* keep = 32'd1 *)
  CC_OBUF _239_ (
    .A(_042_),
    .O(LED[4])
  );
  (* keep = 32'd1 *)
  CC_OBUF _240_ (
    .A(_043_),
    .O(LED[5])
  );
  (* keep = 32'd1 *)
  CC_OBUF _241_ (
    .A(_044_),
    .O(LED[6])
  );
  (* keep = 32'd1 *)
  CC_OBUF _242_ (
    .A(_045_),
    .O(LED[7])
  );
  (* keep = 32'd1 *)
  CC_IBUF _243_ (
    .I(clk_ext),
    .Y(_085_)
  );
  assign _075_[0] = 1'h0;
  assign _076_[6:0] = _075_[7:1];
  assign _078_[0] = 1'h0;
  assign _079_[20:0] = _078_[21:1];
  assign _082_[0] = 1'h0;
  assign _083_[4:0] = _082_[5:1];
endmodule
